name: Dependency Check
on:
  pull_request:                # ← use pull_request, NOT pull_request_target
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check dependent PRs
        uses: gregsdennis/dependencies-action@v1.4.1   # Node-20 build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}