# .github/workflows/dependency-check.yml
name: dependency-check           # workflow name

on:
  # 1️⃣  Runs on every PR so it can block merges
  pull_request:
    types: [opened, synchronize, reopened, edited]
  # 2️⃣  Runs on every push to main so the context
  #     appears on the default branch
  push:
    branches: [main]
  # 3️⃣  (Optional) lets you trigger it manually from Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  dependency-check:              # ← status context = "dependency-check"
    name: dependency-check       # (explicit name keeps it stable)
    runs-on: ubuntu-latest

    steps:
      - name: Evaluate PR dependencies
        uses: gregsdennis/dependencies-action@v1.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}