name: Dependency Check
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check dependent PRs
        uses: gregsdennis/dependencies-action@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}